name: API CI
on: { push: { branches: [ main ] }, pull_request: {} }
jobs:
  build-test-migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - run: npm ci
      - run: npm run build -w @app/api
      - run: npm run prisma:generate
      - run: npm run prisma:migrate -- -w @app/api status || true
