-keep class com.getcapacitor.** { *; }
-keep class com.google.android.gms.** { *; }
-keepclassmembers class * { @android.webkit.JavascriptInterface <methods>; }
-dontwarn okhttp3.**
-dontwarn okio.**
